version: '3'
services:
  server1:
    container_name: server1
    restart: always
    build: .
    ports:
      - '4300:4300'
      - '4301:4301'
    links:
      - redis
      - mongo
  mongo:
    container_name: server1-mongo
    image: 'mongo:4'
  redis:
    container_name: server1-redis
    image: 'redis:4.0.11'